# Generated by Django 5.0 on 2023-12-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=3000)),
            ],
        ),
    ]
